USE Esports
DROP PROCEDURE IF EXISTS createTranslator
GO
DROP PROCEDURE IF EXISTS deleteTranslator
GO
DROP TRIGGER IF EXISTS superRole
GO
DROP TRIGGER IF EXISTS dontInsertIfTeamsFilled
GO

CREATE TRIGGER dontInsertIfTeamsFilled
ON PARTICIPATES_IN INSTEAD OF INSERT 
AS
BEGIN
	DECLARE @count INT
	DECLARE @tournament VARCHAR(50)
	DECLARE @numberOfTeams INT

	SELECT @tournament = tournament FROM INSERTED
	
	SELECT @count = COUNT(*) FROM PARTICIPATES_IN WHERE @tournament = tournament
	SELECT @numberOfTeams = number_teams FROM TOURNAMENT WHERE @tournament = [name]
	
	IF @count >= @numberOfTeams
		RAISERROR('Tournament slots are already filled.',16,1)
	ELSE
		INSERT INTO PARTICIPATES_IN SELECT * FROM INSERTED
END
GO

/*GO
CREATE PROCEDURE createTranslator
AS
BEGIN

CREATE TABLE TRANSLATOR (
role1 VARCHAR(30) PRIMARY KEY,
intvalue INT,
)

INSERT INTO TRANSLATOR VALUES ('Event Manager', 1)
INSERT INTO TRANSLATOR VALUES ('Production crew', 2)
INSERT INTO TRANSLATOR VALUES ('Business Management', 3)
INSERT INTO TRANSLATOR VALUES ('Sales Management', 4)
INSERT INTO TRANSLATOR VALUES ('Partnerships Manager', 4)
INSERT INTO TRANSLATOR VALUES ('Product Manager', 4)
INSERT INTO TRANSLATOR VALUES ('Marketing executive', 5)
INSERT INTO TRANSLATOR VALUES ('Admin', 6)
INSERT INTO TRANSLATOR VALUES ('Observer', 7)
INSERT INTO TRANSLATOR VALUES ('Caster', 7)
END
GO

GO
CREATE PROCEDURE deleteTranslator
AS
BEGIN

DELETE FROM TRANSLATOR

END
GO


GO 
CREATE TRIGGER superRole ON EVENT_STAFF
INSTEAD OF INSERT
AS
BEGIN
	EXEC createTranslator
	IF (SELECT COUNT(*) FROM INSERTED) = 1
		BEGIN
			DECLARE @SUPER_UN AS VARCHAR(25);
			DECLARE @THIS_UN AS VARCHAR(25);
			DECLARE @SUPER_RL INT;
			DECLARE @THIS_RL INT;

			SELECT @THIS_UN = username, @SUPER_UN = super_username FROM inserted;
			IF EXISTS ( SELECT 1 FROM TEAM_STAFF_ROLE WHERE username = @SUPER_UN ) AND EXISTS ( SELECT 1 FROM TEAM_STAFF_ROLE WHERE username = @THIS_UN )
			BEGIN
				SELECT @SUPER_RL = intvalue FROM TEAM_STAFF_ROLE AS TS, TRANSLATOR AS TR WHERE TS.username = @SUPER_UN AND TR.role1 = TS.[role] 
				SELECT @THIS_RL = intvalue FROM TEAM_STAFF_ROLE AS TS, TRANSLATOR AS TR WHERE TS.username = @THIS_UN AND TR.role1 = TS.[role]
				IF @SUPER_RL > @THIS_RL
					BEGIN
						RAISERROR('Delegator role is lower than Delegatee!', 16, 1);
					END
				ELSE
					INSERT INTO EVENT_STAFF SELECT * FROM INSERTED;
			END
		END
	EXEC deleteTranslator
END
GO*/